// @generated by gen-driver.py — S2 driver 盲调用套件。DO NOT EDIT BY HAND.
// 生成器: jobs/97f58082/tmp/gen-driver.py；候选清单与安全标注: s1-cov/driver-candidates.md
// 用例语义: 盲调用（执行即覆盖）——错误被吞掉但错误分支被点亮；
//           命令/插件不存在 → skip；其余任何结果（含业务错误）→ pass。
import type { TestCase } from '../test-runner';
import { invoke } from '@tauri-apps/api/core';
import { getCurrentWindow, Window, getAllWindows, monitorFromPoint } from '@tauri-apps/api/window';
import { getCurrentWebview, Webview } from '@tauri-apps/api/webview';
import * as path from '@tauri-apps/api/path';
import { LogicalSize, LogicalPosition } from '@tauri-apps/api/dpi';

const NOT_IMPLEMENTED = /not (registered|found|implemented|supported|installed|allowed by acl)|command not found|no such|unknown command|unavailable|plugin .*not/i;

let _seq = 0;
const uniq = (p: string) => `${p}_${Date.now().toString(36)}_${++_seq}`;
const delay = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function blind(fn: () => Promise<unknown>): Promise<void> {
  try {
    await fn();
  } catch (e) {
    const m = String((e as Error)?.message ?? e);
    if (NOT_IMPLEMENTED.test(m)) throw new Error('skip: ' + m);
    // 其他错误也是覆盖（错误分支被点亮）——按通过计
  }
}

function driverCase(name: string, fn: () => Promise<unknown>): TestCase {
  return { name: 'driver: ' + name, category: 'driver', timeout: 3000, fn: () => blind(fn) };
}

function sideCase(name: string, fn: () => Promise<unknown>): TestCase {
  return { name: 'side-replay: ' + name, category: 'side-effect', timeout: 5000, fn: () => blind(fn) };
}

function badCase(name: string, fn: () => Promise<unknown>): TestCase {
  return { name: 'bad-input: ' + name, category: 'driver', timeout: 5000, fn: () => blind(fn) };
}

// ══════ SAFE: driver 盲调用 ══════
export const driverTests: TestCase[] = [
  driverCase('cmd.echo', async () => {
    await invoke('echo', { message: 'driver' });
  }),
  driverCase('cmd.log_operation', async () => {
    await invoke('log_operation', { event: 'driver', payload: 'driver-payload' });
  }),
  driverCase('cmd.dummy_command', async () => {
    await invoke('dummy_command');
  }),
  driverCase('cmd.create_counter', async () => {
    await invoke('create_counter', { start: 1 });
  }),
  driverCase('cmd.increment_counter', async () => {
    await invoke('increment_counter', { amount: 2 });
  }),
  driverCase('cmd.get_counter_value', async () => {
    await invoke('get_counter_value');
  }),
  driverCase('cmd.count_webview_windows', async () => {
    await invoke('count_webview_windows');
  }),
  driverCase('cmd.get_tracked_window_events', async () => {
    await invoke('get_tracked_window_events');
  }),
  driverCase('cmd.get_tracked_menu_events', async () => {
    await invoke('get_tracked_menu_events');
  }),
  driverCase('cmd.get_tracked_run_events', async () => {
    await invoke('get_tracked_run_events');
  }),
  driverCase('cmd.get_last_new_window_url', async () => {
    await invoke('get_last_new_window_url');
  }),
  driverCase('cmd.console_log', async () => {
    await invoke('console_log', { level: 'info', message: 'driver' });
  }),
  driverCase('cmd.flush_console_log', async () => {
    await invoke('flush_console_log');
  }),
  driverCase('cmd.clear_console_log', async () => {
    await invoke('clear_console_log');
  }),
  driverCase('cmd.emit_test_event', async () => {
    await invoke('emit_test_event');
  }),
  driverCase('cmd.clear_tracked_events', async () => {
    await invoke('clear_tracked_events');
  }),
  driverCase('cmd.setup_app_listener', async () => {
    await invoke('setup_app_listener');
  }),
  driverCase('cmd.set_deny_new_window.off', async () => {
    await invoke('set_deny_new_window', { deny: false });
  }),
  driverCase('cmd.set_deny_new_window.on+off', async () => {
    await invoke('set_deny_new_window', { deny: true }); await invoke('set_deny_new_window', { deny: false });
  }),
  driverCase('cmd.set_download_test_mode', async () => {
    await invoke('set_download_test_mode', { mode: 'accept' });
  }),
  driverCase('cmd.cookie_test', async () => {
    await invoke('cookie_test');
  }),
  driverCase('cmd.test_local_storage', async () => {
    await invoke('test_local_storage');
  }),
  driverCase('cmd.test_persisted_scope', async () => {
    await invoke('test_persisted_scope');
  }),
  driverCase('cmd.clear_persisted_scope', async () => {
    await invoke('clear_persisted_scope');
  }),
  driverCase('cmd.test_eval', async () => {
    await invoke('test_eval');
  }),
  driverCase('cmd.test_async_spawn', async () => {
    await invoke('test_async_spawn');
  }),
  driverCase('cmd.test_web_page_snapshot', async () => {
    await invoke('test_web_page_snapshot');
  }),
  driverCase('cmd.test_create_pdf.cache', async () => {
    const d = await path.appCacheDir(); await invoke('test_create_pdf', { path: d + '/' + uniq('pdf') + '.pdf' });
  }),
  driverCase('cmd.transparent_test_start', async () => {
    await invoke('transparent_test_start', { windowId: uniq('transp') });
  }),
  driverCase('cmd.clear_window_state', async () => {
    await invoke('clear_window_state');
  }),
  driverCase('cmd.devtools_open_only', async () => {
    await invoke('devtools_open_only');
  }),
  driverCase('cmd.devtools_close_only', async () => {
    await invoke('devtools_close_only');
  }),
  driverCase('cmd.devtools_test', async () => {
    await invoke('devtools_test');
  }),
  driverCase('cmd.simulate_tray_click', async () => {
    await invoke('simulate_tray_click');
  }),
  driverCase('cmd.sentry_test_breadcrumb', async () => {
    await invoke('sentry_test_breadcrumb');
  }),
  driverCase('cmd.sentry_test_panic', async () => {
    await invoke('sentry_test_panic');
  }),
  driverCase('cmd.create_borderless_window', async () => {
    await invoke('create_borderless_window', { windowId: uniq('bw') }); await delay(400);
  }),
  driverCase('cmd.create_transparent_window', async () => {
    await invoke('create_transparent_window', { windowId: uniq('tw'), effect: 'Blur', radius: 25 }); await delay(400);
  }),
  driverCase('cmd.create_transparent_borderless_window', async () => {
    await invoke('create_transparent_borderless_window', { windowId: uniq('tbw') }); await delay(400);
  }),
  driverCase('cmd.create_window_no_throttle', async () => {
    await invoke('create_window_no_throttle', { windowId: uniq('nthr') }); await delay(400);
  }),
  driverCase('cmd.create_window_with_custom_ua', async () => {
    await invoke('create_window_with_custom_ua', { windowId: uniq('cua'), userAgent: 'DriverUA/1.0' }); await delay(400);
  }),
  driverCase('cmd.create_isolated_window', async () => {
    await invoke('create_isolated_window', { windowId: uniq('iso'), dataSuffix: 'd', url: '/hello.html' }); await delay(400);
  }),
  driverCase('cmd.create_ui_ability_window', async () => {
    await invoke('create_ui_ability_window', { windowId: uniq('uia') }); await delay(600);
  }),
  driverCase('cmd.create_transparent_ui_ability_window', async () => {
    await invoke('create_transparent_ui_ability_window', { windowId: uniq('tuia') }); await delay(600);
  }),
  driverCase('cmd.create_ui_ability_windows_x3', async () => {
    await invoke('create_ui_ability_windows_x3', { windowId: uniq('uia3') }); await delay(800);
  }),
  driverCase('cmd.create_ohos_test_webview', async () => {
    await invoke('create_ohos_test_webview', { windowId: uniq('ohwv'), label: 'driver webview' }); await delay(600);
  }),
  driverCase('cmd.close_all_test_windows.cleanup', async () => {
    await invoke('close_all_test_windows'); await delay(300);
  }),
  driverCase('clipboard.writeText', async () => {
    const { writeText } = await import('@tauri-apps/plugin-clipboard-manager'); await writeText('driver-' + uniq('cb'));
  }),
  driverCase('clipboard.writeHtml', async () => {
    await invoke('plugin:clipboard-manager|write_html', { html: '<b>driver</b>' });
  }),
  driverCase('clipboard.clear', async () => {
    const { clear } = await import('@tauri-apps/plugin-clipboard-manager'); await clear();
  }),
  driverCase('clipboard.readText', async () => {
    const { readText } = await import('@tauri-apps/plugin-clipboard-manager'); await readText();
  }),
  driverCase('clipboard.readImage.empty', async () => {
    await invoke('plugin:clipboard-manager|read_image');
  }),
  driverCase('os.hostname', async () => {
    const { hostname } = await import('@tauri-apps/plugin-os'); await hostname();
  }),
  driverCase('os.locale', async () => {
    const { locale } = await import('@tauri-apps/plugin-os'); await locale();
  }),
  driverCase('log.trace', async () => {
    const { trace } = await import('@tauri-apps/plugin-log'); await trace('driver trace');
  }),
  driverCase('log.info', async () => {
    const { info } = await import('@tauri-apps/plugin-log'); await info('driver info');
  }),
  driverCase('log.warn', async () => {
    const { warn } = await import('@tauri-apps/plugin-log'); await warn('driver warn');
  }),
  driverCase('log.error', async () => {
    const { error } = await import('@tauri-apps/plugin-log'); await error('driver error');
  }),
  driverCase('notification.isPermissionGranted', async () => {
    const { isPermissionGranted } = await import('@tauri-apps/plugin-notification'); await isPermissionGranted();
  }),
  driverCase('notification.active', async () => {
    const { active } = await import('@tauri-apps/plugin-notification'); await active();
  }),
  driverCase('notification.pending', async () => {
    const { pending } = await import('@tauri-apps/plugin-notification'); await pending();
  }),
  driverCase('notification.channels', async () => {
    const { channels } = await import('@tauri-apps/plugin-notification'); await channels();
  }),
  driverCase('fs.write+read.roundtrip', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); const d = await path.appCacheDir(); const f = d + '/' + uniq('fs') + '.txt'; await fs.writeTextFile(f, 'driver'); await fs.readTextFile(f); await fs.remove(f);
  }),
  driverCase('fs.readDir.cache', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); await fs.readDir(await path.appCacheDir());
  }),
  driverCase('fs.exists.cache', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); await fs.exists(await path.appCacheDir());
  }),
  driverCase('fs.mkdir+remove.roundtrip', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); const d = await path.appCacheDir(); const sub = d + '/' + uniq('dir'); await fs.mkdir(sub); await fs.remove(sub, { recursive: true });
  }),
  driverCase('fs.readTextFile.nonexistent', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); await fs.readTextFile((await path.appCacheDir()) + '/no-such-' + uniq('f') + '.txt');
  }),
  driverCase('fs.stat.cache', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); await fs.stat(await path.appCacheDir());
  }),
  driverCase('fs.metadata.cache', async () => {
    const fs = await import('@tauri-apps/plugin-fs'); await fs.metadata(await path.appCacheDir());
  }),
  driverCase('http.fetch.refused', async () => {
    const { fetch } = await import('@tauri-apps/plugin-http'); await fetch('http://127.0.0.1:1/', { connectTimeout: 2000 });
  }),
  driverCase('http.fetch.localhost', async () => {
    const { fetch } = await import('@tauri-apps/plugin-http'); await fetch('http://localhost:3005/', { connectTimeout: 5000 });
  }),
  driverCase('updater.check', async () => {
    const { check } = await import('@tauri-apps/plugin-updater'); await check();
  }),
  driverCase('store.lifecycle', async () => {
    const { load } = await import('@tauri-apps/plugin-store'); const s = await load(uniq('store') + '.json'); await s.set('k', 'v'); await s.get('k'); await s.has('k'); await s.keys(); await s.values(); await s.length(); await s.entries(); await s.reload(); await s.save(); await s.delete('k'); await s.clear(); await s.close();
  }),
  driverCase('store.reset', async () => {
    const { load } = await import('@tauri-apps/plugin-store'); const s = await load(uniq('store2') + '.json'); await s.set('k1', 1); await s.set('k2', 2); await s.reset(); await s.close();
  }),
  driverCase('sql.sqlite.memory', async () => {
    const { Database } = await import('@tauri-apps/plugin-sql'); const db = await Database.load('sqlite::memory:'); await db.execute('CREATE TABLE IF NOT EXISTS drv (id INTEGER PRIMARY KEY, v TEXT)'); await db.execute('INSERT INTO drv (v) VALUES ($1)', ['driver']); await db.select('SELECT * FROM drv'); await db.close();
  }),
  driverCase('sql.sqlite.bad-sql', async () => {
    const { Database } = await import('@tauri-apps/plugin-sql'); const db = await Database.load('sqlite::memory:'); await db.execute('NOT VALID SQL'); await db.close();
  }),
  driverCase('websocket.connect.refused', async () => {
    const { connect } = await import('@tauri-apps/plugin-websocket'); const ws = await connect('ws://127.0.0.1:1'); await ws.disconnect();
  }),
  driverCase('upload.download.localhost', async () => {
    const { download } = await import('@tauri-apps/plugin-upload'); const d = await path.appCacheDir(); await download('http://localhost:3005/', d + '/' + uniq('dl') + '.html', (p) => {});
  }),
  driverCase('global-shortcut.register+unregister', async () => {
    const { register, isRegistered, unregister, unregisterAll } = await import('@tauri-apps/plugin-global-shortcut'); await register('CommandOrControl+Shift+F13'); await isRegistered('CommandOrControl+Shift+F13'); await unregister('CommandOrControl+Shift+F13'); await unregisterAll();
  }),
  driverCase('global-shortcut.bad-key', async () => {
    const { register } = await import('@tauri-apps/plugin-global-shortcut'); await register('not-a-real-key');
  }),
  driverCase('deep-link.getCurrent', async () => {
    const { getCurrent } = await import('@tauri-apps/plugin-deep-link'); await getCurrent();
  }),
  driverCase('deep-link.getCurrentListeners', async () => {
    const { getCurrentListeners } = await import('@tauri-apps/plugin-deep-link'); await getCurrentListeners();
  }),
  driverCase('opener.open_path.nonexistent', async () => {
    const { openPath } = await import('@tauri-apps/plugin-opener'); await openPath((await path.appCacheDir()) + '/no-such-' + uniq('p'));
  }),
  driverCase('opener.revealItemInDir.nonexistent', async () => {
    const { revealItemInDir } = await import('@tauri-apps/plugin-opener'); await revealItemInDir((await path.appCacheDir()) + '/no-such-' + uniq('r'));
  }),
  driverCase('autostart.lifecycle', async () => {
    const { enable, disable, isEnabled } = await import('@tauri-apps/plugin-autostart'); await isEnabled(); await enable(); await isEnabled(); await disable();
  }),
  driverCase('window-state.save+restore', async () => {
    await invoke('plugin:window-state|save_window_state'); await invoke('plugin:window-state|restore_state');
  }),
  driverCase('haptics.vibrate', async () => {
    await invoke('plugin:haptics|vibrate', { duration: 15 });
  }),
  driverCase('haptics.impactFeedback', async () => {
    await invoke('plugin:haptics|impact_feedback', { style: 'light' });
  }),
  driverCase('haptics.notificationFeedback', async () => {
    await invoke('plugin:haptics|notification_feedback', { type: 'success' });
  }),
  driverCase('haptics.selectionFeedback', async () => {
    await invoke('plugin:haptics|selection_feedback');
  }),
  driverCase('geolocation.checkPermissions', async () => {
    const { checkPermissions } = await import('@tauri-apps/plugin-geolocation'); await checkPermissions();
  }),
  driverCase('geolocation.clearWatch.bogus', async () => {
    const { clearWatch } = await import('@tauri-apps/plugin-geolocation'); await clearWatch(999999);
  }),
  driverCase('geolocation.getCurrentPosition.timeout', async () => {
    const { getCurrentPosition } = await import('@tauri-apps/plugin-geolocation'); await getCurrentPosition({ timeout: 2000, maximumAge: 0 });
  }),
  driverCase('biometric.status', async () => {
    await invoke('plugin:biometric|status');
  }),
  driverCase('nfc.scan.ndef', async () => {
    await invoke('plugin:nfc|scan', { kind: { type: 'ndef' } });
  }),
  driverCase('barcode-scanner.cancel', async () => {
    await invoke('plugin:barcode-scanner|cancel');
  }),
  driverCase('barcode-scanner.open_app_settings', async () => {
    await invoke('plugin:barcode-scanner|open_app_settings');
  }),
  driverCase('huawei-account.silent_login', async () => {
    await invoke('plugin:huawei-account|silent_login');
  }),
  driverCase('huawei-account.logout', async () => {
    await invoke('plugin:huawei-account|logout');
  }),
  driverCase('positioner.moveWindow', async () => {
    await invoke('plugin:positioner|move_window', { position: 'topRight' });
  }),
  driverCase('cli.getMatches', async () => {
    const { getMatches } = await import('@tauri-apps/plugin-cli'); await getMatches();
  }),
  driverCase('sentry.breadcrumb', async () => {
    await invoke('plugin:sentry|breadcrumb', { message: 'driver breadcrumb' });
  }),
  driverCase('sentry.envelope', async () => {
    await invoke('plugin:sentry|envelope', { envelope: 'driver' });
  }),
  driverCase('shell.Command.create', async () => {
    const { Command } = await import('@tauri-apps/plugin-shell'); const cmd = Command.create('echo-args'); await cmd.spawn(); await cmd.kill();
  }),
  driverCase('win.innerSize', async () => {
    await getCurrentWindow().innerSize();
  }),
  driverCase('win.outerSize', async () => {
    await getCurrentWindow().outerSize();
  }),
  driverCase('win.innerPosition', async () => {
    await getCurrentWindow().innerPosition();
  }),
  driverCase('win.outerPosition', async () => {
    await getCurrentWindow().outerPosition();
  }),
  driverCase('win.isFullscreen', async () => {
    await getCurrentWindow().isFullscreen();
  }),
  driverCase('win.isFocused', async () => {
    await getCurrentWindow().isFocused();
  }),
  driverCase('win.isDecorated', async () => {
    await getCurrentWindow().isDecorated();
  }),
  driverCase('win.isMaximized', async () => {
    await getCurrentWindow().isMaximized();
  }),
  driverCase('win.isMinimized', async () => {
    await getCurrentWindow().isMinimized();
  }),
  driverCase('win.isResizable', async () => {
    await getCurrentWindow().isResizable();
  }),
  driverCase('win.isMaximizable', async () => {
    await getCurrentWindow().isMaximizable();
  }),
  driverCase('win.isMinimizable', async () => {
    await getCurrentWindow().isMinimizable();
  }),
  driverCase('win.isClosable', async () => {
    await getCurrentWindow().isClosable();
  }),
  driverCase('win.isVisible', async () => {
    await getCurrentWindow().isVisible();
  }),
  driverCase('win.isAlwaysOnTop', async () => {
    await getCurrentWindow().isAlwaysOnTop();
  }),
  driverCase('win.isEnabled', async () => {
    await getCurrentWindow().isEnabled();
  }),
  driverCase('win.title', async () => {
    await getCurrentWindow().title();
  }),
  driverCase('win.scaleFactor', async () => {
    await getCurrentWindow().scaleFactor();
  }),
  driverCase('win.currentMonitor', async () => {
    await getCurrentWindow().currentMonitor();
  }),
  driverCase('win.availableMonitors', async () => {
    await getCurrentWindow().availableMonitors();
  }),
  driverCase('win.primaryMonitor', async () => {
    await getCurrentWindow().primaryMonitor();
  }),
  driverCase('win.monitorFromPoint', async () => {
    await monitorFromPoint(0, 0);
  }),
  driverCase('win.theme', async () => {
    await getCurrentWindow().theme();
  }),
  driverCase('win.setTitle', async () => {
    await getCurrentWindow().setTitle('Tauri API');
  }),
  driverCase('win.setDecorations', async () => {
    await getCurrentWindow().setDecorations(true);
  }),
  driverCase('win.setAlwaysOnTop', async () => {
    await getCurrentWindow().setAlwaysOnTop(false);
  }),
  driverCase('win.setSkipTaskbar', async () => {
    await getCurrentWindow().setSkipTaskbar(false);
  }),
  driverCase('win.setResizable', async () => {
    await getCurrentWindow().setResizable(true);
  }),
  driverCase('win.setMaximizable', async () => {
    await getCurrentWindow().setMaximizable(true);
  }),
  driverCase('win.setMinimizable', async () => {
    await getCurrentWindow().setMinimizable(true);
  }),
  driverCase('win.setClosable', async () => {
    await getCurrentWindow().setClosable(true);
  }),
  driverCase('win.setShadow', async () => {
    await getCurrentWindow().setShadow(true);
  }),
  driverCase('win.setCursorVisible', async () => {
    await getCurrentWindow().setCursorVisible(true);
  }),
  driverCase('win.setCursorIcon', async () => {
    await getCurrentWindow().setCursorIcon('default');
  }),
  driverCase('win.setCursorGrab', async () => {
    await getCurrentWindow().setCursorGrab(false);
  }),
  driverCase('win.cursorPosition', async () => {
    await getCurrentWindow().cursorPosition();
  }),
  driverCase('win.setIgnoreCursorEvents', async () => {
    await getCurrentWindow().setIgnoreCursorEvents(false);
  }),
  driverCase('win.setFocusable', async () => {
    await getCurrentWindow().setFocusable(true);
  }),
  driverCase('win.setContentProtected', async () => {
    await getCurrentWindow().setContentProtected(true);
  }),
  driverCase('win.setBackgroundColor', async () => {
    await getCurrentWindow().setBackgroundColor('#FFFFFF');
  }),
  driverCase('win.setAlwaysOnBottom', async () => {
    await getCurrentWindow().setAlwaysOnBottom(false);
  }),
  driverCase('win.setProgressBar', async () => {
    await getCurrentWindow().setProgressBar(0.5); await getCurrentWindow().setProgressBar(0);
  }),
  driverCase('win.setBadgeCount', async () => {
    await getCurrentWindow().setBadgeCount(1); await getCurrentWindow().setBadgeCount(0);
  }),
  driverCase('win.setBadgeLabel', async () => {
    await getCurrentWindow().setBadgeLabel('drv'); await getCurrentWindow().setBadgeLabel(null);
  }),
  driverCase('win.requestUserAttention', async () => {
    await getCurrentWindow().requestUserAttention(1);
  }),
  driverCase('win.setSizeConstraints', async () => {
    await getCurrentWindow().setSizeConstraints(null);
  }),
  driverCase('win.setFocus', async () => {
    await getCurrentWindow().setFocus();
  }),
  driverCase('win.setFullscreen.off', async () => {
    await getCurrentWindow().setFullscreen(false);
  }),
  driverCase('win.setEffects.blur', async () => {
    await getCurrentWindow().setEffects({ effects: ['blur'], radius: 20 });
  }),
  driverCase('win.clearEffects', async () => {
    await getCurrentWindow().clearEffects();
  }),
  driverCase('win.setMinSize', async () => {
    await getCurrentWindow().setMinSize(new LogicalSize(200, 150));
  }),
  driverCase('win.setMaxSize', async () => {
    await getCurrentWindow().setMaxSize(new LogicalSize(4096, 2160));
  }),
  driverCase('win.setTheme.dark+light', async () => {
    await getCurrentWindow().setTheme('dark'); await getCurrentWindow().setTheme('light');
  }),
  driverCase('win.listen.onResized', async () => {
    const w = getCurrentWindow(); const un = await w.listen('tauri://resize', () => {}); un();
  }),
  driverCase('win.listen.onMoved', async () => {
    const w = getCurrentWindow(); const un = await w.listen('tauri://move', () => {}); un();
  }),
  driverCase('win.onFocusChanged', async () => {
    const w = getCurrentWindow(); const un = await w.onFocusChanged(() => {}); un();
  }),
  driverCase('win.onScaleChanged', async () => {
    const w = getCurrentWindow(); const un = await w.onScaleChanged(() => {}); un();
  }),
  driverCase('win.onThemeChanged', async () => {
    const w = getCurrentWindow(); const un = await w.onThemeChanged(() => {}); un();
  }),
  driverCase('win.getAllWindows', async () => {
    await getAllWindows();
  }),
  driverCase('win.getByLabel.nonexistent', async () => {
    await Window.getByLabel('no-such-' + uniq('lbl'));
  }),
  driverCase('float.setSize+setPosition', async () => {
    const label = uniq('flt'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.setSize(new LogicalSize(320, 240)); await w.setPosition(new LogicalPosition(60, 60)); await w.innerSize(); await w.outerPosition(); } if (w) { await w.destroy(); }
  }),
  driverCase('float.maximize+unmaximize', async () => {
    const label = uniq('fltm'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.maximize(); await delay(400); await w.unmaximize(); await delay(300); } if (w) { await w.destroy(); }
  }),
  driverCase('float.minimize+unminimize', async () => {
    const label = uniq('fltn'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.minimize(); await delay(400); await w.unminimize(); await delay(300); } if (w) { await w.destroy(); }
  }),
  driverCase('float.toggleMaximize', async () => {
    const label = uniq('fltt'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.toggleMaximize(); await delay(400); await w.toggleMaximize(); await delay(300); } if (w) { await w.destroy(); }
  }),
  driverCase('float.setEnabled.toggle', async () => {
    const label = uniq('flte'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.setEnabled(false); await delay(200); await w.setEnabled(true); } if (w) { await w.destroy(); }
  }),
  driverCase('float.destroy', async () => {
    const label = uniq('fltd'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.destroy(); }
  }),
  driverCase('float.hide+show+center', async () => {
    const label = uniq('flth'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.hide(); await delay(300); await w.show(); await delay(300); await w.center(); } if (w) { await w.destroy(); }
  }),
  driverCase('float.setFocus+alwaysOnTop', async () => {
    const label = uniq('fltf'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.setAlwaysOnTop(true); await delay(200); await w.setAlwaysOnTop(false); await w.setFocus(); } if (w) { await w.destroy(); }
  }),
  driverCase('webview.position', async () => {
    await getCurrentWebview().position();
  }),
  driverCase('webview.size', async () => {
    await getCurrentWebview().size();
  }),
  driverCase('webview.setPosition', async () => {
    const p = await getCurrentWebview().position(); await getCurrentWebview().setPosition(p);
  }),
  driverCase('webview.setSize', async () => {
    const s = await getCurrentWebview().size(); await getCurrentWebview().setSize(s);
  }),
  driverCase('webview.setZoom', async () => {
    await getCurrentWebview().setZoom(1.0);
  }),
  driverCase('webview.setAutoResize', async () => {
    await getCurrentWebview().setAutoResize({ width: true, height: true });
  }),
  driverCase('webview.setBackgroundColor', async () => {
    await getCurrentWebview().setBackgroundColor('#FFFFFF');
  }),
  driverCase('webview.clearAllBrowsingData', async () => {
    await getCurrentWebview().clearAllBrowsingData();
  }),
  driverCase('webview.setFocus', async () => {
    await getCurrentWebview().setFocus();
  }),
  driverCase('webview.hide+show', async () => {
    await getCurrentWebview().hide(); await delay(200); await getCurrentWebview().show();
  }),
  driverCase('webview.listen.onDragDropEvent', async () => {
    const wv = getCurrentWebview(); const un = await wv.onDragDropEvent(() => {}); un();
  }),
  driverCase('webview.getByLabel.nonexistent', async () => {
    await Webview.getByLabel('no-such-' + uniq('wv'));
  }),
  driverCase('app.getVersion', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.getVersion();
  }),
  driverCase('app.getName', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.getName();
  }),
  driverCase('app.getTauriVersion', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.getTauriVersion();
  }),
  driverCase('app.getIdentifier', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.getIdentifier();
  }),
  driverCase('app.getBundleType', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.getBundleType();
  }),
  driverCase('app.defaultWindowIcon', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.defaultWindowIcon();
  }),
  driverCase('app.supportsMultipleWindows', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.supportsMultipleWindows();
  }),
  driverCase('app.setTheme', async () => {
    const appApi = await import('@tauri-apps/api/app'); await appApi.setTheme('light'); await appApi.setTheme(null);
  }),
  driverCase('path.appCacheDir', async () => {
    await path.appCacheDir();
  }),
  driverCase('path.appConfigDir', async () => {
    await path.appConfigDir();
  }),
  driverCase('path.appDataDir', async () => {
    await path.appDataDir();
  }),
  driverCase('path.appLocalDataDir', async () => {
    await path.appLocalDataDir();
  }),
  driverCase('path.appLogDir', async () => {
    await path.appLogDir();
  }),
  driverCase('path.audioDir', async () => {
    await path.audioDir();
  }),
  driverCase('path.cacheDir', async () => {
    await path.cacheDir();
  }),
  driverCase('path.configDir', async () => {
    await path.configDir();
  }),
  driverCase('path.dataDir', async () => {
    await path.dataDir();
  }),
  driverCase('path.documentDir', async () => {
    await path.documentDir();
  }),
  driverCase('path.downloadDir', async () => {
    await path.downloadDir();
  }),
  driverCase('path.pictureDir', async () => {
    await path.pictureDir();
  }),
  driverCase('path.tempDir', async () => {
    await path.tempDir();
  }),
  driverCase('path.resourceDir', async () => {
    await path.resourceDir();
  }),
  driverCase('path.runtimeDir', async () => {
    await path.runtimeDir();
  }),
  driverCase('event.emit+listen', async () => {
    const { emit, listen } = await import('@tauri-apps/api/event'); const un = await listen('driver-event', () => {}); await emit('driver-event'); un();
  }),
  driverCase('menu.Menu.default', async () => {
    const { Menu } = await import('@tauri-apps/api/menu'); const m = await Menu.default(); await m.items();
  }),
];

// ══════ SIDE: side-effect 复放（无断言，放套件末尾） ══════
export const sideReplayTests: TestCase[] = [
  sideCase('side.win.setEffects.acrylic', async () => {
    await getCurrentWindow().setEffects({ effects: ['acrylic'] }); await delay(400);
  }),
  sideCase('side.win.setEffects.mica', async () => {
    await getCurrentWindow().setEffects({ effects: ['mica'] }); await delay(400);
  }),
  sideCase('side.win.setEffects.blur+radius', async () => {
    await getCurrentWindow().setEffects({ effects: ['blur'], radius: 40 }); await delay(400);
  }),
  sideCase('side.win.clearEffects.restore', async () => {
    await getCurrentWindow().clearEffects(); await delay(300);
  }),
  sideCase('side.win.setTitle.roundtrip', async () => {
    await getCurrentWindow().setTitle('side-effect replay'); await delay(300); await getCurrentWindow().setTitle('Tauri API');
  }),
  sideCase('side.win.setCursorIcon.progress', async () => {
    await getCurrentWindow().setCursorIcon('progress'); await delay(300); await getCurrentWindow().setCursorIcon('default');
  }),
  sideCase('side.opener.openUrl.localhost', async () => {
    const { openUrl } = await import('@tauri-apps/plugin-opener'); await openUrl('http://localhost:3005/'); await delay(500);
  }),
  sideCase('side.opener.openPath.cache', async () => {
    const { openPath } = await import('@tauri-apps/plugin-opener'); await openPath(await path.appCacheDir()); await delay(500);
  }),
  sideCase('side.notification.notify', async () => {
    const n = await import('@tauri-apps/plugin-notification'); const granted = await n.isPermissionGranted(); if (granted) { await n.sendNotification({ title: 'driver side-effect', body: 'notify replay' }); } await delay(500);
  }),
  sideCase('side.notification.channel.create+delete', async () => {
    const n = await import('@tauri-apps/plugin-notification'); const id = 'drv-' + uniq('ch'); await n.createChannel({ id, name: 'driver-channel' }); await delay(200); await n.removeChannel(id);
  }),
  sideCase('side.geolocation.watchPosition.short', async () => {
    const g = await import('@tauri-apps/plugin-geolocation'); const un = await g.watchPosition(() => {}, () => {}); await delay(1500); un();
  }),
  sideCase('side.geolocation.requestPermissions', async () => {
    const { requestPermissions } = await import('@tauri-apps/plugin-geolocation'); await requestPermissions();
  }),
  sideCase('side.clipboard.writeImage.tiny', async () => {
    await invoke('plugin:clipboard-manager|write_image', { image: 'no-such-image' });
  }),
  sideCase('side.haptics.vibrate.long', async () => {
    await invoke('plugin:haptics|vibrate', { duration: 100 }); await delay(200);
  }),
  sideCase('side.shell.open.help', async () => {
    const { open } = await import('@tauri-apps/plugin-shell'); await open('help');
  }),
  sideCase('side.updater.download_and_install', async () => {
    const { check } = await import('@tauri-apps/plugin-updater'); const u = await check(); if (u) { await u.downloadAndInstall(); }
  }),
  sideCase('side.dialog.message.last', async () => {
    const { message } = await import('@tauri-apps/plugin-dialog'); await message('driver side-effect replay done');
  }),
];

// ══════ BAD: S3 坏输入错误用例（design.md §三矩阵，serde/lookup/越界/不可达/权限分支） ══════
export const badInputTests: TestCase[] = [
  badCase('bad.set_size.string_size', async () => {
    await invoke('plugin:window|set_size', { label: 'main', logical: 'not-an-object' });
  }),
  badCase('bad.set_size.numeric_label', async () => {
    await invoke('plugin:window|set_size', { label: 12345, logical: { width: 100, height: 100 } });
  }),
  badCase('bad.create_window.numeric_id', async () => {
    await invoke('create_borderless_window', { windowId: 12345 });
  }),
  badCase('bad.set_zoom.string_value', async () => {
    await invoke('plugin:webview|set_webview_zoom', { label: 'main', zoom: 'not-a-number' });
  }),
  badCase('bad.fetch.null_url', async () => {
    await invoke('plugin:http|fetch', { url: null, method: 'GET' });
  }),
  badCase('bad.badge_count.negative', async () => {
    await invoke('plugin:window|set_badge_count', { label: 'main', count: -5 });
  }),
  badCase('bad.badge_label.long', async () => {
    await invoke('plugin:window|set_badge_label', { label: 'main', badgeLabel: 'x'.repeat(300) });
  }),
  badCase('bad.window.set_title.ghost', async () => {
    await invoke('plugin:window|set_title', { label: 'ghost-' + uniq('w'), title: 'x' });
  }),
  badCase('bad.window.maximize.ghost', async () => {
    await invoke('plugin:window|maximize', { label: 'ghost-' + uniq('w') });
  }),
  badCase('bad.window.destroy.ghost', async () => {
    await invoke('plugin:window|destroy', { label: 'ghost-' + uniq('w') });
  }),
  badCase('bad.webview.position.ghost', async () => {
    await invoke('plugin:webview|set_webview_position', { label: 'ghost-' + uniq('w'), x: 0, y: 0 });
  }),
  badCase('bad.getByLabel.ghost', async () => {
    await Window.getByLabel('ghost-' + uniq('w')); await Webview.getByLabel('ghost-' + uniq('w'));
  }),
  badCase('bad.create_then_destroy_then_op', async () => {
    const label = uniq('btd'); await invoke('create_borderless_window', { windowId: label }); await delay(600); const w = await Window.getByLabel(label); if (w) { await w.destroy(); } await delay(300); await invoke('plugin:window|maximize', { label });
  }),
  badCase('bad.set_size.negative_dims', async () => {
    await invoke('plugin:window|set_size', { label: 'main', logical: { width: -100, height: -100 } });
  }),
  badCase('bad.set_size_constraints.inverted', async () => {
    await invoke('plugin:window|set_size_constraints', { label: 'main', constraints: { minWidth: 5000, maxWidth: 100 } });
  }),
  badCase('bad.create_window.empty_label', async () => {
    await invoke('create_borderless_window', { windowId: '' });
  }),
  badCase('bad.create_window.long_label', async () => {
    await invoke('create_borderless_window', { windowId: 'x'.repeat(500) });
  }),
  badCase('bad.setZoom.negative', async () => {
    await getCurrentWebview().setZoom(-1);
  }),
  badCase('bad.monitorFromPoint.far', async () => {
    await monitorFromPoint(1e9, 1e9);
  }),
  badCase('bad.fetch.refused_port', async () => {
    const { fetch } = await import('@tauri-apps/plugin-http'); await fetch('http://127.0.0.1:1/');
  }),
  badCase('bad.fetch.blackhole', async () => {
    const { fetch } = await import('@tauri-apps/plugin-http'); await fetch('http://192.0.2.1:1/');
  }),
  badCase('bad.fs.read_dir.nonexistent', async () => {
    await invoke('plugin:fs|read_dir', { path: '/no-such-dir-' + uniq('d') });
  }),
  badCase('bad.fs.mkdir.empty_path', async () => {
    await invoke('plugin:fs|mkdir', { path: '' });
  }),
  badCase('bad.fs.out_of_scope', async () => {
    await invoke('plugin:fs|read_text_file', { path: '/proc/version' });
  }),
  badCase('bad.clipboard.read_image.unsupported', async () => {
    await invoke('plugin:clipboard-manager|read_image');
  }),
  badCase('bad.window.set_icon.nonexistent', async () => {
    await invoke('plugin:window|set_icon', { label: 'main', icon: 'no-such-icon-path' });
  }),
];
